/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FileObjects_constants.h"

namespace MyMpp {

const FileObjectsConstants g_FileObjects_constants;

FileObjectsConstants::FileObjectsConstants() {
}

} // namespace

