/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FileObjects_CONSTANTS_H
#define FileObjects_CONSTANTS_H

#include "FileObjects_types.h"

namespace MyMpp {

class FileObjectsConstants {
 public:
  FileObjectsConstants();

};

extern const FileObjectsConstants g_FileObjects_constants;

} // namespace

#endif
